# Importação de Todas as Bibliotecas Usadas e do Dataset Filtrado

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
from pprint import pprint
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.metrics import RocCurveDisplay

In [2]:
colunas = ['Q001','Q002','Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 
           'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024', 'Q025', 'TP_PRESENCA_LC', 'TP_PRESENCA_CH', 'TP_PRESENCA_CN', 'TP_PRESENCA_MT', 
           'TP_FAIXA_ETARIA', 'TP_SEXO','TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_ESCOLA', 'TP_ST_CONCLUSAO', 'TP_ENSINO', 'IN_TREINEIRO', 
           'TP_DEPENDENCIA_ADM_ESC', 'NU_ANO']

df = pd.read_parquet("enem_parquet", columns = colunas)

In [3]:
df

,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,...,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_ESCOLA,TP_ST_CONCLUSAO,TP_ENSINO,IN_TREINEIRO,TP_DEPENDENCIA_ADM_ESC,NU_ANO
0,B,B,A,A,2.0,A,A,B,C,A,...,13,M,1,3,1,1,NaN,0,NaN,2019
1,C,E,B,B,4.0,C,A,B,C,A,...,8,M,1,1,1,1,1.0,0,NaN,2019
2,E,E,B,C,2.0,B,A,B,B,A,...,13,F,1,3,1,1,1.0,0,NaN,2019
3,C,E,B,D,4.0,E,A,C,C,A,...,10,F,1,1,1,1,NaN,0,NaN,2019
4,E,E,C,C,3.0,G,A,C,D,B,...,7,F,1,1,1,1,1.0,0,NaN,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21678167,B,B,A,B,6.0,B,A,B,C,A,...,14,F,1,2,1,1,NaN,0,NaN,2023
21678168,H,E,F,B,5.0,C,A,B,B,A,...,9,F,1,3,1,1,NaN,0,NaN,2023
21678169,E,G,D,D,4.0,G,A,C,D,B,...,3,F,1,1,1,1,NaN,0,NaN,2023
21678170,B,G,B,D,4.0,B,A,B,C,A,...,1,F,1,3,1,3,NaN,1,NaN,2023
21678171,G,G,E,D,4.0,L,B,E,D,B,...,1,F,1,1,1,3,NaN,1,NaN,2023

# Tratando os Dados

In [4]:
def transformar_colunas(df):

    colunas = [
    'Q001','Q002','Q003','Q004','Q006','Q007','Q008','Q009','Q010',
    'Q011','Q012','Q013','Q014','Q015','Q016','Q017','Q018',
    'Q019','Q020','Q021', 'Q022','Q023','Q024','Q025'
    ]

    letras = {l:i for i,l in enumerate(string.ascii_uppercase)}

    for col in colunas:

        df[col] = df[col].map(letras)

        df[col] = df[col].fillna(-1)

    return df

In [5]:
df = transformar_colunas(df)

In [6]:
df

,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,...,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_ESCOLA,TP_ST_CONCLUSAO,TP_ENSINO,IN_TREINEIRO,TP_DEPENDENCIA_ADM_ESC,NU_ANO
0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,2.0,0.0,...,13,M,1,3,1,1,NaN,0,NaN,2019
1,2.0,4.0,1.0,1.0,4.0,2.0,0.0,1.0,2.0,0.0,...,8,M,1,1,1,1,1.0,0,NaN,2019
2,4.0,4.0,1.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,...,13,F,1,3,1,1,1.0,0,NaN,2019
3,2.0,4.0,1.0,3.0,4.0,4.0,0.0,2.0,2.0,0.0,...,10,F,1,1,1,1,NaN,0,NaN,2019
4,4.0,4.0,2.0,2.0,3.0,6.0,0.0,2.0,3.0,1.0,...,7,F,1,1,1,1,1.0,0,NaN,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21678167,1.0,1.0,0.0,1.0,6.0,1.0,0.0,1.0,2.0,0.0,...,14,F,1,2,1,1,NaN,0,NaN,2023
21678168,7.0,4.0,5.0,1.0,5.0,2.0,0.0,1.0,1.0,0.0,...,9,F,1,3,1,1,NaN,0,NaN,2023
21678169,4.0,6.0,3.0,3.0,4.0,6.0,0.0,2.0,3.0,1.0,...,3,F,1,1,1,1,NaN,0,NaN,2023
21678170,1.0,6.0,1.0,3.0,4.0,1.0,0.0,1.0,2.0,0.0,...,1,F,1,3,1,3,NaN,1,NaN,2023
21678171,6.0,6.0,4.0,3.0,4.0,11.0,1.0,4.0,3.0,1.0,...,1,F,1,1,1,3,NaN,1,NaN,2023

In [7]:
df["IDADE_ALTA"] = (df["TP_FAIXA_ETARIA"] > 5).astype(int)

df["ACESSO_DIGITAL"] = (
    (df["Q024"] > 0) & (df["Q025"] == 1)  
).astype(int)

df['PAIS_SEM_INSTRUCAO'] = (
    (df['Q001'] == 0) & (df['Q002'] == 0)
).astype(int)

df['SEM_DIGITAL'] = (
    (df['Q024'] == 0) & (df['Q025'] == 0)
).astype(int)

df['FAMILIA_GRANDE_POBRE'] = (
    (df['Q005'] >= 4) &   
    (df['Q006'] <= 2)     
).astype(int)

df['SCORE_BENS_RELEVANTES'] = (
    df['Q010'] +   
    df['Q014'] +   
    df['Q021'] +   
    df['Q024'] +  
    df['Q025']     
)

df['TREINEIRO_JOVEM'] = (
    (df['IN_TREINEIRO'] == 1) &
    (df['TP_FAIXA_ETARIA'] <= 2)   
).astype(int)

df['FAMILIA_QUALIFICADA'] = (
    (df['Q003'] >= 4) |   # pai em ocupação qualificada
    (df['Q004'] >= 4)     # mãe em ocupação qualificada
).astype(int)

df['SCORE_RISCO'] = (
    (df['Q006'] <= 2).astype(int) * 2 +   # renda baixa — peso maior
    (df['Q004'] >= 2).astype(int) +        # trabalha
    (df['IN_TREINEIRO'] == 1).astype(int)* 2 + # treineiro — peso maior
    (df['IDADE_ALTA'] == 1).astype(int)        # idade alta
)

df['MORA_SOZINHO'] = (df['Q005'] == 1).astype(int)

df['PUBLICO_CURSANDO'] = (
    (df['TP_ESCOLA'] == 1) &       # escola pública
    (df['TP_ST_CONCLUSAO'] == 1)   # ainda cursando
).astype(int)

bens = ['Q007','Q008','Q009','Q010','Q011','Q012','Q013','Q014']
df['SEM_BENS'] = (df[bens].max(axis=1) == 0).astype(int)

In [8]:
df['TP_ENSINO'] = df['TP_ENSINO'].fillna(0)
df['TP_DEPENDENCIA_ADM_ESC'] = df['TP_DEPENDENCIA_ADM_ESC'].fillna(0)

dicionario_genero = {'F': 0, 'M': 1}
df['TP_SEXO'] = df['TP_SEXO'].map(dicionario_genero)

In [9]:
FALTOU = (
    (df['TP_PRESENCA_CH'] == 0) & 
    (df['TP_PRESENCA_LC'] == 0) & 
    (df['TP_PRESENCA_CN'] == 0) & 
    (df['TP_PRESENCA_MT'] == 0)
)

df['FALTOU'] = FALTOU.astype(int)

In [10]:
df

,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,...,SEM_DIGITAL,FAMILIA_GRANDE_POBRE,SCORE_BENS_RELEVANTES,TREINEIRO_JOVEM,FAMILIA_QUALIFICADA,SCORE_RISCO,MORA_SOZINHO,PUBLICO_CURSANDO,SEM_BENS,FALTOU
0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,2.0,0.0,...,0,0,3.0,0,0,3,0,1,0,1
1,2.0,4.0,1.0,1.0,4.0,2.0,0.0,1.0,2.0,0.0,...,0,1,1.0,0,0,3,0,1,0,1
2,4.0,4.0,1.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,...,0,0,1.0,0,0,4,0,1,0,1
3,2.0,4.0,1.0,3.0,4.0,4.0,0.0,2.0,2.0,0.0,...,0,0,4.0,0,0,2,0,1,0,0
4,4.0,4.0,2.0,2.0,3.0,6.0,0.0,2.0,3.0,1.0,...,0,0,4.0,0,0,2,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21678167,1.0,1.0,0.0,1.0,6.0,1.0,0.0,1.0,2.0,0.0,...,0,1,3.0,0,0,3,0,1,0,0
21678168,7.0,4.0,5.0,1.0,5.0,2.0,0.0,1.0,1.0,0.0,...,1,1,1.0,0,1,3,0,1,0,0
21678169,4.0,6.0,3.0,3.0,4.0,6.0,0.0,2.0,3.0,1.0,...,0,0,5.0,0,0,1,0,1,0,0
21678170,1.0,6.0,1.0,3.0,4.0,1.0,0.0,1.0,2.0,0.0,...,0,1,1.0,1,0,5,0,0,0,0
21678171,6.0,6.0,4.0,3.0,4.0,11.0,1.0,4.0,3.0,1.0,...,0,0,6.0,1,1,3,0,0,0,0

In [11]:
#df.to_parquet("dados_treino.parquet")

# Treinando Random Forest

In [12]:
df_reduzido = df.sample(n=100_000, random_state=42)

Features = ['Q001','Q002','Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 
           'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024', 'Q025', 'TP_FAIXA_ETARIA', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_ESCOLA',
            "IDADE_ALTA", "ACESSO_DIGITAL", 'PAIS_SEM_INSTRUCAO', 'SEM_DIGITAL', 'FAMILIA_GRANDE_POBRE', 'SCORE_BENS_RELEVANTES',
            'TREINEIRO_JOVEM', 'FAMILIA_QUALIFICADA', 'SCORE_RISCO', 'MORA_SOZINHO', 'PUBLICO_CURSANDO', 'SEM_BENS', 'NU_ANO',
            'TP_ST_CONCLUSAO', 'TP_DEPENDENCIA_ADM_ESC', 'TP_SEXO']

X = df_reduzido[Features]
y = df_reduzido['FALTOU']

x_train, x_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\nTreino: {len(x_train):,} | Teste: {len(x_test):,}")
print(f"Taxa de falta no treino: {y_train.mean():.3f}")
print(f"Taxa de falta no teste:  {y_test.mean():.3f}")

Treino: 80,000 | Teste: 20,000
Taxa de falta no treino: 0.333
Taxa de falta no teste:  0.333

In [13]:
rf = RandomForestClassifier(n_estimators = 100, max_depth = 30, random_state=42)

rf.fit(x_train, y_train)

print('Ein: %0.4f' % (1 - accuracy_score(y_train, rf.predict(x_train))))
print('Eout: %0.4f' % (1 - accuracy_score(y_test, rf.predict(x_test))))
print(classification_report(y_test, rf.predict(x_test)))

Ein: 0.0024
Eout: 0.2932
              precision    recall  f1-score   support

           0       0.74      0.87      0.80     13338
           1       0.59      0.38      0.46      6662

    accuracy                           0.71     20000
   macro avg       0.67      0.62      0.63     20000
weighted avg       0.69      0.71      0.69     20000

# Tratando Overfit

In [14]:
n_estimators = [int(x) for x in np.linspace(start=20, stop = 70, num=6)]
max_features = ['sqrt', 'log2', 8]
max_depth = [int(x) for x in np.linspace(start=10, stop = 40, num=4)]
max_depth.append(None)

param_grid = {
    'n_estimators' : n_estimators,
    'max_features' : max_features,
    'max_depth' : max_depth
}

pprint(param_grid)

{'max_depth': [10, 20, 30, 40, None],
 'max_features': ['sqrt', 'log2', 8],
 'n_estimators': [20, 30, 40, 50, 60, 70]}

In [15]:
# rf = RandomForestClassifier()

# cv_rf = GridSearchCV(estimator = rf, param_grid = param_grid, cv = 5, verbose=2, n_jobs=-1)

# cv_rf.fit(x_train, y_train)

# print('Ein: %0.4f' % (1 - accuracy_score(y_train, cv_rf.predict(x_train))))
# print('Eout: %0.4f' % (1 - accuracy_score(y_test, cv_rf.predict(x_test))))
# print(classification_report(y_test, cv_rf.predict(x_test)))

# print(cv_rf.best_estimator_)

# Treinando Usando Parâmetros Atualizados

In [16]:
rf_final = RandomForestClassifier(
    n_estimators=100,        
    max_depth=15,            
    max_features='log2',     
    min_samples_split=20,    
    min_samples_leaf=50,      
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

In [17]:
rf_final.fit(x_train, y_train)

y_pred_train = rf_final.predict(x_train)
y_pred_test  = rf_final.predict(x_test)

ein  = 1 - accuracy_score(y_train, y_pred_train)
eout = 1 - accuracy_score(y_test,  y_pred_test)

print(f"\nEin:  {ein:.4f}")
print(f"Eout: {eout:.4f}")
print(f"Gap:  {eout - ein:.4f}  {'⚠️ overfitting' if eout - ein > 0.05 else '✅ ok'}")
print("\n" + classification_report(y_test, y_pred_test))

Ein:  0.3262
Eout: 0.3404
Gap:  0.0141  ✅ ok

              precision    recall  f1-score   support

           0       0.81      0.64      0.71     13338
           1       0.49      0.70      0.58      6662

    accuracy                           0.66     20000
   macro avg       0.65      0.67      0.65     20000
weighted avg       0.71      0.66      0.67     20000

# Verificando a Probabilidade do Aluno ir à Prova

In [18]:
y_prob = rf_final.predict_proba(x_test)[:,1]
roc_auc_score(y_test, y_prob)

0.7343625468102075

In [ ]:
RocCurveDisplay.from_predictions(
    y_test,
    y_prob
)

# Verificando Quantidade de Faltas por Ano

In [ ]:
faltas_por_ano = df.groupby('NU_ANO')['FALTOU'].sum()

plt.figure(figsize=(8,5))
faltas_por_ano.plot(kind='bar', color='skyblue')
plt.title('Quantidade de Faltas por Ano')
plt.xlabel('Ano')
plt.ylabel('Número de Faltas')
plt.xticks(rotation=0)
plt.show()

# Testando Sem Passar NU_ANO

In [20]:
Features = ['Q001','Q002','Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 
           'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024', 'Q025', 'TP_FAIXA_ETARIA', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_ESCOLA',
            "IDADE_ALTA", "ACESSO_DIGITAL", 'PAIS_SEM_INSTRUCAO', 'SEM_DIGITAL', 'FAMILIA_GRANDE_POBRE', 'SCORE_BENS_RELEVANTES',
            'TREINEIRO_JOVEM', 'FAMILIA_QUALIFICADA', 'SCORE_RISCO', 'MORA_SOZINHO', 'PUBLICO_CURSANDO', 'SEM_BENS', 
            'TP_ST_CONCLUSAO', 'TP_DEPENDENCIA_ADM_ESC', 'TP_SEXO']

X = df_reduzido[Features]
y = df_reduzido['FALTOU']

x_train, x_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\nTreino: {len(x_train):,} | Teste: {len(x_test):,}")
print(f"Taxa de falta no treino: {y_train.mean():.3f}")
print(f"Taxa de falta no teste:  {y_test.mean():.3f}")

rf_final = RandomForestClassifier(
    n_estimators=100,        
    max_depth=15,            
    max_features='log2',     
    min_samples_split=20,    
    min_samples_leaf=50,      
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_final.fit(x_train, y_train)

y_pred_train = rf_final.predict(x_train)
y_pred_test  = rf_final.predict(x_test)

ein  = 1 - accuracy_score(y_train, y_pred_train)
eout = 1 - accuracy_score(y_test,  y_pred_test)

print(f"\nEin:  {ein:.4f}")
print(f"Eout: {eout:.4f}")
print(f"Gap:  {eout - ein:.4f}  {'⚠️ overfitting' if eout - ein > 0.05 else '✅ ok'}")
print("\n" + classification_report(y_test, y_pred_test))

Treino: 80,000 | Teste: 20,000
Taxa de falta no treino: 0.333
Taxa de falta no teste:  0.333

Ein:  0.3428
Eout: 0.3579
Gap:  0.0151  ✅ ok

              precision    recall  f1-score   support

           0       0.80      0.62      0.70     13338
           1       0.47      0.69      0.56      6662

    accuracy                           0.64     20000
   macro avg       0.64      0.65      0.63     20000
weighted avg       0.69      0.64      0.65     20000

# Testando Sem o Ano de 2020

In [21]:
indices_2020 = df[df['NU_ANO'] == 2020].index

df.drop(indices_2020, inplace=True)

In [22]:
df_reduzido = df.sample(n=100_000, random_state=42)

Features = ['Q001','Q002','Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 
           'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024', 'Q025', 'TP_FAIXA_ETARIA', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_ESCOLA',
            "IDADE_ALTA", "ACESSO_DIGITAL", 'PAIS_SEM_INSTRUCAO', 'SEM_DIGITAL', 'FAMILIA_GRANDE_POBRE', 'SCORE_BENS_RELEVANTES',
            'TREINEIRO_JOVEM', 'FAMILIA_QUALIFICADA', 'SCORE_RISCO', 'MORA_SOZINHO', 'PUBLICO_CURSANDO', 'SEM_BENS', 'NU_ANO',
            'TP_ST_CONCLUSAO', 'TP_DEPENDENCIA_ADM_ESC', 'TP_SEXO']

X = df_reduzido[Features]
y = df_reduzido['FALTOU']

x_train, x_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\nTreino: {len(x_train):,} | Teste: {len(x_test):,}")
print(f"Taxa de falta no treino: {y_train.mean():.3f}")
print(f"Taxa de falta no teste:  {y_test.mean():.3f}")

rf_final = RandomForestClassifier(
    n_estimators=100,        
    max_depth=15,            
    max_features='log2',     
    min_samples_split=20,    
    min_samples_leaf=50,      
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_final.fit(x_train, y_train)

y_pred_train = rf_final.predict(x_train)
y_pred_test  = rf_final.predict(x_test)

ein  = 1 - accuracy_score(y_train, y_pred_train)
eout = 1 - accuracy_score(y_test,  y_pred_test)

print(f"\nEin:  {ein:.4f}")
print(f"Eout: {eout:.4f}")
print(f"Gap:  {eout - ein:.4f}  {'⚠️ overfitting' if eout - ein > 0.05 else '✅ ok'}")
print("\n" + classification_report(y_test, y_pred_test))

Treino: 80,000 | Teste: 20,000
Taxa de falta no treino: 0.265
Taxa de falta no teste:  0.265

Ein:  0.3414
Eout: 0.3524
Gap:  0.0110  ✅ ok

              precision    recall  f1-score   support

           0       0.86      0.63      0.72     14706
           1       0.40      0.71      0.51      5294

    accuracy                           0.65     20000
   macro avg       0.63      0.67      0.62     20000
weighted avg       0.74      0.65      0.67     20000

# Testando Sem 2020 e Sem Passar NU_ANO

In [23]:
Features = ['Q001','Q002','Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 
           'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024', 'Q025', 'TP_FAIXA_ETARIA', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_ESCOLA',
            "IDADE_ALTA", "ACESSO_DIGITAL", 'PAIS_SEM_INSTRUCAO', 'SEM_DIGITAL', 'FAMILIA_GRANDE_POBRE', 'SCORE_BENS_RELEVANTES',
            'TREINEIRO_JOVEM', 'FAMILIA_QUALIFICADA', 'SCORE_RISCO', 'MORA_SOZINHO', 'PUBLICO_CURSANDO', 'SEM_BENS',
            'TP_ST_CONCLUSAO', 'TP_DEPENDENCIA_ADM_ESC', 'TP_SEXO']

X = df_reduzido[Features]
y = df_reduzido['FALTOU']

x_train, x_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\nTreino: {len(x_train):,} | Teste: {len(x_test):,}")
print(f"Taxa de falta no treino: {y_train.mean():.3f}")
print(f"Taxa de falta no teste:  {y_test.mean():.3f}")

rf_final = RandomForestClassifier(
    n_estimators=100,        
    max_depth=15,            
    max_features='log2',     
    min_samples_split=20,    
    min_samples_leaf=50,      
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_final.fit(x_train, y_train)

y_pred_train = rf_final.predict(x_train)
y_pred_test  = rf_final.predict(x_test)

ein  = 1 - accuracy_score(y_train, y_pred_train)
eout = 1 - accuracy_score(y_test,  y_pred_test)

print(f"\nEin:  {ein:.4f}")
print(f"Eout: {eout:.4f}")
print(f"Gap:  {eout - ein:.4f}  {'⚠️ overfitting' if eout - ein > 0.05 else '✅ ok'}")
print("\n" + classification_report(y_test, y_pred_test))

Treino: 80,000 | Teste: 20,000
Taxa de falta no treino: 0.265
Taxa de falta no teste:  0.265

Ein:  0.3492
Eout: 0.3586
Gap:  0.0094  ✅ ok

              precision    recall  f1-score   support

           0       0.85      0.62      0.72     14706
           1       0.40      0.71      0.51      5294

    accuracy                           0.64     20000
   macro avg       0.63      0.66      0.61     20000
weighted avg       0.73      0.64      0.66     20000